### ISSUE TITLE
`Schema`和`ArgumentExtractor`自动生成

### ISSUE THREAD

**Issue by jxnu-liguobin** [SymphonyQL/SymphonyQL#9]
- [x] Scala 3 Schema 自动生成
- [x] Scala 3 ArgumentExtractor 自动生成
- [ ] Java Schema 自动生成
- [ ] Java ArgumentExtractor 自动生成

由于我们的目标是Code First，应该尽可能自动生成。
- `ArgumentExtractor` 用于从AST解析请求参数，若请求参数是已知POJO，`ArgumentExtractor` 是确定的
- `Schema`是描述 GraphQL 接口的结构，若接口输入输出的类型是已知POJO，`Schema` 也是确定的
因此可以自动生成。Java 通过注解、Scala通过宏或者Compiler插件、sbt插件代码生成实现

**Comment by jxnu-liguobin** [comment]
考虑方便测试和使用，我们至少应具备Scala3 Schema自动生成，预计增加模块`modules/scala-derives`
优先级：Scala Schema ->  Scala ArgumentExtractor -> Java Schema -> Java ArgumentExtractor

**Comment by He-Pin** [comment]
就是，不然累死人了。不过Java。。。。
